name: Daily Data Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run script to update data
        run: |
          # Run your script here that makes the API call, fetches data, and writes it to a CSV file
          # Example command: python update_data.py
          python scripts/get_games.py    

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes from remote repository
        run: |
          git pull origin main || echo "No new changes to pull"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update data - ${{ github.run_id }}" || echo "No changes to commit"

      - name: Push changes to master branch
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GIT }}  # Use the GitHub Personal Access Token stored as a secret
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GIT }}@github.com/${{ github.repository }}.git
          git push origin HEAD:master
